### ISSUE TITLE
这个仓库还在维护吗？是否还接收pr以及发布新包呢

### ISSUE THREAD

**Issue by zreo0** [xuezier/apollo-client#3]
想确认下签名部分是否有问题，默认使用 secret 验签无法通过，手动修改后可以通过。因为是 egg-apollo-client 依赖的包，项目要是改就得俩一起改了，能直接发就最好了

**Comment by xuezier** [comment]
有问题可以提交 issue 或 pr 注明，收到后会处理的哈
